GiftStore/Models/AboutUs.cs
namespace GiftStore.Models
{
    public class AboutUs
    {
       public int Id { get; set; }
        public string txt { get; set; }
    }
}

GiftStore/Models/ContactUs.cs
namespace GiftStore.Models
{
	public class ContactUs
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string Email { get; set; }
		public string Message { get; set; }
		public DateTime CreatedAt { get; set; }
	}
}

GiftStore/Models/Favorite.cs
namespace GiftStore.Models
{
	public class Favorite
	{

		public int Id { get; set; }

		// ربط الهدية بالمفضلة
		public int GiftId { get; set; }
		public Gift Gift { get; set; }

		// ربط المستخدم بالمفضلة
		public string UserId { get; set; }  // UserId سيكون من جدول المستخدمين في Identity
		public ApplicationUser User { get; set; } // علاقة بالمستخدم


	}
}

GiftStore/Models/Gift.cs
using Microsoft.AspNetCore.Http.HttpResults;
using NuGet.Protocol.Plugins;
using System.ComponentModel.DataAnnotations.Schema;

namespace GiftStore.Models
{
    public class Gift
    {
        public int GiftId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string?ImageUrl { get; set; }
        [ForeignKey("Category")]
        public int CategoryId { get; set; }
        public Category? Category { get; set; }
		public string AvailableColors { get; set; } // مثل "أحمر;أزرق;أخضر"
		public decimal discount { get; set; }
		public int numberOfItems { get; set; }
	}
}

GiftStore/Models/ViewModels/GiftViewModel.cs
namespace GiftStore.Models.ViewModels
{
    public class GiftViewModel
    {
        public IEnumerable<Gift> gifts { get; set; }
        public IEnumerable<Category> Categories { get; set; }

        public IEnumerable<Slider> sliders { get; set; }

		public List<Gift> RelatedGifts { get; set; } // الهدايا المشابهة

		public string SearchTerm { get; set; } // إضافة خاصية البحث
        public decimal? Price { get; set; }

		public int GiftId { get; set; } // Store the selected gift ID

		public Gift Gift { get; set; } // تفاصيل الهدية

		public int SelectedQuantity { get; set; } // لاختيار عدد العناصر
		public string SelectedColor { get; set; } // لاختيار اللون من قائمة
		public string CustomMessage { get; set; } // لإضافة رسالة مخصصة

		// Dropdown for available colors
		public List<string> AvailableColors { get; set; }
	}
}

GiftStore/Areas/Administrator/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GiftStore.Data;
using GiftStore.Models;

namespace GiftStore.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    public class AboutUsController : Controller
    {
        private readonly MyDbContext _context;

        public AboutUsController(MyDbContext context)
        {
            _context = context;
        }

        // GET: Administrator/AboutUs
        public async Task<IActionResult> Index()
        {
              return _context.aboutUs != null ? 
                          View(await _context.aboutUs.ToListAsync()) :
                          Problem("Entity set 'MyDbContext.aboutUs'  is null.");
        }

        // GET: Administrator/AboutUs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.aboutUs == null)
            {
                return NotFound();
            }

            var aboutUs = await _context.aboutUs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aboutUs == null)
            {
                return NotFound();
            }

            return View(aboutUs);
        }

        // GET: Administrator/AboutUs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Administrator/AboutUs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,txt")] AboutUs aboutUs)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aboutUs);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aboutUs);
        }

        // GET: Administrator/AboutUs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.aboutUs == null)
            {
                return NotFound();
            }

            var aboutUs = await _context.aboutUs.FindAsync(id);
            if (aboutUs == null)
            {
                return NotFound();
            }
            return View(aboutUs);
        }

        // POST: Administrator/AboutUs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,txt")] AboutUs aboutUs)
        {
            if (id != aboutUs.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aboutUs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AboutUsExists(aboutUs.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aboutUs);
        }

        // GET: Administrator/AboutUs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.aboutUs == null)
            {
                return NotFound();
            }

            var aboutUs = await _context.aboutUs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aboutUs == null)
            {
                return NotFound();
            }

            return View(aboutUs);
        }

        // POST: Administrator/AboutUs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.aboutUs == null)
            {
                return Problem("Entity set 'MyDbContext.aboutUs'  is null.");
            }
            var aboutUs = await _context.aboutUs.FindAsync(id);
            if (aboutUs != null)
            {
                _context.aboutUs.Remove(aboutUs);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AboutUsExists(int id)
        {
          return (_context.aboutUs?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

GiftStore/Areas/Administrator/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GiftStore.Data;
using GiftStore.Models;

namespace GiftStore.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    public class ContactUsController : Controller
    {
        private readonly MyDbContext _context;

        public ContactUsController(MyDbContext context)
        {
            _context = context;
        }

        // GET: Administrator/ContactUs
        public async Task<IActionResult> Index()
        {
              return _context.contactUs != null ? 
                          View(await _context.contactUs.ToListAsync()) :
                          Problem("Entity set 'MyDbContext.contactUs'  is null.");
        }

        // GET: Administrator/ContactUs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.contactUs == null)
            {
                return NotFound();
            }

            var contactUs = await _context.contactUs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contactUs == null)
            {
                return NotFound();
            }

            return View(contactUs);
        }

        // GET: Administrator/ContactUs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Administrator/ContactUs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,Message,CreatedAt")] ContactUs contactUs)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contactUs);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(contactUs);
        }

        // GET: Administrator/ContactUs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.contactUs == null)
            {
                return NotFound();
            }

            var contactUs = await _context.contactUs.FindAsync(id);
            if (contactUs == null)
            {
                return NotFound();
            }
            return View(contactUs);
        }

        // POST: Administrator/ContactUs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,Message,CreatedAt")] ContactUs contactUs)
        {
            if (id != contactUs.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contactUs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactUsExists(contactUs.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contactUs);
        }

        // GET: Administrator/ContactUs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.contactUs == null)
            {
                return NotFound();
            }

            var contactUs = await _context.contactUs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contactUs == null)
            {
                return NotFound();
            }

            return View(contactUs);
        }

        // POST: Administrator/ContactUs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.contactUs == null)
            {
                return Problem("Entity set 'MyDbContext.contactUs'  is null.");
            }
            var contactUs = await _context.contactUs.FindAsync(id);
            if (contactUs != null)
            {
                _context.contactUs.Remove(contactUs);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactUsExists(int id)
        {
          return (_context.contactUs?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

GiftStore/ViewComponents/GiftViewComponent.cs
using GiftStore.Data;
using Microsoft.AspNetCore.Mvc;

namespace GiftStore.ViewComponents
{
	public class GiftViewComponent:ViewComponent
	{

		private MyDbContext db;
		public GiftViewComponent(MyDbContext _db)
		{
			db = _db;
		}
		public IViewComponentResult Invoke()
		{
			var gifts = db.gifts.Take(8).ToList();
			return View(gifts);
		}
	}
}

GiftStore/ViewComponents/SliderViewComponent.cs
using GiftStore.Data;
using Microsoft.AspNetCore.Mvc;

namespace GiftStore.ViewComponents
{
	public class SliderViewComponent:ViewComponent
	{
		private MyDbContext db;
		public SliderViewComponent(MyDbContext _db)
		{
			db = _db;
		}
		public IViewComponentResult Invoke()
		{
			var sliders= db.sliders.ToList();
			return View(sliders);
		}
	}
}

GiftStore/ViewComponents/TestimonialViewComponent.cs
using GiftStore.Data;
using Microsoft.AspNetCore.Mvc;

namespace GiftStore.ViewComponents
{
    public class TestimonialViewComponent:ViewComponent
    {
        private MyDbContext db;
        public TestimonialViewComponent(MyDbContext _db)
        {
            db = _db;
        }
        public IViewComponentResult Invoke()
        {
            var Testimonial = db.testimonials.ToList();
            return View(Testimonial);
        }
    }
}

GiftStore/Views/Home/AboutUs.cshtml
@model IEnumerable<GiftStore.Models.AboutUs>

@{
    ViewData["Title"] = "AboutUs";
}


@*<p>
    <a asp-action="Create">Create New</a>
</p>*@


<div class="container container-xxl">
	<div class="row">
		<div class="col-lg-6">
			<div class="card border-0 hover-zoom-in">
				<div class="image-box-4">


					<img class="lazy-image img-fluid lazy-image" src="~/images1/pink-cute-teddy-with-pink-beautiful-gift-box_1010706-479.jpg" data-src="" width="960" height="640" alt="">
				</div>
				<div class="">
				</div>
			</div>

		</div>
		<div class="col-lg-6 px-xxl-18 mt-12 mt-lg-0">
			<h2 class="mb-8">About Us</h2>
			
				@foreach (var item in Model)
				{
				<p>
					@Html.DisplayFor(modelItem => item.txt) .....
				</p>
				}
			
@*			<p class="mb-xl-16">If I fell in love with a woman for an artistic reason, or from the point of view of my work, I think it would rob her of something. We live in an era of globalization and the era of the woman. Never in the history of the world have women <span class="text-body-emphasis">been more in control of their destiny.</span></p>
*@			<div class="row">
				<div class="col-md-6">
					<div class="d-flex align-items-start">
						<div class="d-none">
							<svg class="icon fs-2">
								<use xlink:href="#"></use>
							</svg>
						</div>
						<div>
							<h3 class="fs-5 mb-6">Message</h3>
							<div class="fs-6">
								<p class="mb-6 fs-15px">Send us a text & an ambassador will respond when available.</p> <p class="m-0 fs-6 fw-bold text-primary">1-814-251-9966</p>
							</div>
						</div>
					</div>

				</div>
				<div class="col-md-6 pt-9 pt-md-0">
					<div class="d-flex align-items-start">
						<div class="d-none">
							<svg class="icon fs-2">
								<use xlink:href="#"></use>
							</svg>
						</div>
						<div>
							<h3 class="fs-5 mb-6">Store Hours</h3>
							<div class="fs-6">
								<dl class="d-flex mb-0"><dt class="pe-3 fs-6 text-body-emphasis fw-500" style="width: 110px">Mon – Fri:</dt><dd class="mb-0"> 08:30 – 20:00</dd></dl><dl class="d-flex mb-0"><dt class="pe-3 fs-6 text-body-emphasis fw-500" style="width: 110px">Sat & Sun:</dt><dd class="mb-0"> 09:30 – 21:30</dd></dl>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>

@*@foreach (var item in Model)
{
    
@Html.DisplayFor(modelItem => item.txt)
       
}*@






@*<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.txt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.txt)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>*@

GiftStore/Views/Home/AddTestimonial.cshtml
@{
    ViewData["Title"] = "AddTestimonial";
}

<h1>Add Testimonial</h1>

@if (ViewBag.Message != null)
{
    <p>@ViewBag.Message</p>
}

<form asp-action="AddTestimonial" method="post">
    <div class="form-group">
        <label for="Content">Add your testimonial :)</label>
        <textarea id="Content" name="Content" class="form-control" rows="4" maxlength="500" required></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>

GiftStore/Views/Home/ContactUs.cshtml
@model GiftStore.Models.ContactUs
@{
    ViewData["Title"] = "ContactUs";
}

<h1>ContactUs</h1>

<div class="row">
    <div class="col-md-4">

<form asp-action="ContactUs" method="post">
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" required/>
    </div>

    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" required/>
    </div>

            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" required />
            </div>

            <button type="submit" class="btn btn-primary">Send</button>

</form>
    </div>
</div>
@*    <input type="submit" value="Submit" class="btn btn-primary" />
*@

GiftStore/Views/Home/Favorites.cshtml
@model IEnumerable<GiftStore.Models.Favorite>

@{
    ViewData["Title"] = "Favorites";
}

<h1>Favorites</h1>
<a class="btn btn-primary" asp-action="Gifts" asp-controller="Home">Back to gifts page</a>

<section>
	<div class="container pt-12 pb-lg-16 pb-16">


		

		@*<div class="text-center position-relative pt-12 pt-lg-17 pb-11 pb-lg-14 mx-auto" style="max-width:700px" data-animate="fadeInUp">
		<form id="filterForm" method="get" asp-action="Gifts">
		<div class="btn-group" role="group" aria-label="Categories">
		<button type="submit" name="categoryId" value="" class="btn btn-secondary">All Categories</button>
		@foreach (var category in Model.Categories)
		{
		<button type="submit" name="categoryId" value="@category.Id" class="btn btn-primary">@category.Name</button>
		}

		</div>
		<div class="col-lg-4 col-md-12 d-flex align-items-center justify-content-center">
		<input type="text" name="searchTerm" value="@Model.SearchTerm" class="form-control me-2" placeholder="Search products..." />
		<input type="number" name="price" value="@Model.Price" class="form-control me-2" placeholder="Max Price" step="0.01" />
		<button type="submit" class="btn btn-info">Search</button>
		</div>

		</form>
		</div>*@



		@*<div class="text-center position-relative pt-12 pt-lg-17 pb-11 pb-lg-14 mx-auto" style="max-width:700px" data-animate="fadeInUp">
		<form id="filterForm" method="get" asp-action="Gifts">
		<!-- أزرار التصنيفات -->
		<div class="btn-group mb-3" role="group" aria-label="Categories">
		<button type="submit" name="categoryId" value="" class="btn btn-secondary">All Categories</button>
		@foreach (var category in Model.Categories)
		{
		<button type="submit" name="categoryId" value="@category.Id" class="btn btn-primary">@category.Name</button>
		}
		</div>

		<!-- البحث اليدوي وتحديد السعر الأقصى -->
		<div class="row justify-content-center align-items-center">
		<div class="col-md-4 mb-3">
		<input type="text" name="searchTerm" value="@Model.SearchTerm" class="form-control" placeholder="Search products..." />
		</div>
		<div class="col-md-4 mb-3">
		<input type="number" name="price" value="@Model.Price" class="form-control" placeholder="Max Price" step="0.01" />
		</div>
		<div class="col-md-2 mb-3">
		<button type="submit" class="btn btn-secondary  w-1000">Search</button>
		</div>
		</div>
		</form>
		</div>*@





		<div class="row gy-8">

			@foreach (var item in Model)
			{
				<div class="col-lg-3 col-sm-6 col-12">
					<div class="card card-product grid-2 bg-transparent border-0" data-animate="fadeInUp">
						<figure class="card-img-top position-relative mb-7 overflow-hidden">
							<a asp-action="GiftDetails" asp-controller="Home" asp-route-id="@item.GiftId" class="hover-zoom-in d-block" title="Shield Conditioner">
								<img src="@item.Gift.ImageUrl" class="img-fluid lazy-image w-100" alt="Shield Conditioner" width="270" height="360" style="object-fit: cover; width: 270px; height: 360px;">
							</a>
							@if (item.Gift.discount != 0)
							{
								<div class="position-absolute product-flash z-index-2 "><span class="badge badge-product-flash on-sale bg-primary">-@item.Gift.discount%</span></div>
							}
							<div class="position-absolute d-flex z-index-2 product-actions  vertical">


								@*<form asp-action="AddToFavorites" asp-controller="Home" method="post">
							<input type="hidden" name="giftId" value="@product.Id" />
							<button type="submit">أضف إلى المفضلة</button>
							</form>*@

								<form asp-action="RemoveFromFavorites" method="post">
									<input type="hidden" name="giftId" value="@item.GiftId" />
									<button type="submit" class="text-body-emphasis bg-body bg-dark-hover text-light-hover rounded-circle square product-action shadow-sm wishlist sm"
											data-bs-toggle="tooltip"
											data-bs-placement="left"
											data-bs-title="Remove From Wishlist">
										<svg class="icon icon-star-light">
											<use xlink:href="#icon-star-light"></use>
										</svg>
									</button>
								</form>

								@*<a class="text-body-emphasis bg-body bg-dark-hover text-light-hover rounded-circle square product-action shadow-sm wishlist sm" href="#" data-bs-toggle="tooltip" data-bs-placement="left" data-bs-title="Add To Wishlist">
							<svg class="icon icon-star-light">
							<use xlink:href="#icon-star-light"></use>
							</svg>
							</a>*@

							</div>
@*							<a href="#" class="btn btn-add-to-cart btn-dark btn-hover-bg-primary btn-hover-border-primary position-absolute z-index-2 text-nowrap btn-sm px-6 py-3 lh-2">Add To Cart</a>
*@						</figure>
						<div class="card-body text-center p-0">






							<span class="d-flex align-items-center price text-body-emphasis fw-bold justify-content-center mb-3 fs-6">
								<del class=" text-body fw-500 me-4 fs-13px">$40.00</del>
								<ins class="text-decoration-none">$ @item.Gift.Price</ins>
							</span>

							<h4 class="product-title card-title text-primary-hover text-body-emphasis fs-15px fw-500 mb-3"><a class="text-decoration-none text-reset" asp-action="GiftDetails" asp-controller="Home" asp-route-id="@item.GiftId">@item.Gift.Name</a></h4>
						</div>
					</div>

				</div>

			}
		</div>

	</div>
</section>

GiftStore/Views/Home/Index.cshtml
@model GiftStore.Models.ViewModels.GiftViewModel
@{
    ViewData["Title"] = "Home Page";
}	
	<main id="content" class="wrapper layout-page">
	@await Component.InvokeAsync("Slider")

		<section>
			<div class="container pt-12 pb-lg-16 pb-16">
				<div class="text-center position-relative pt-12 pt-lg-17 pb-11 pb-lg-14 mx-auto" style="max-width:700px" data-animate="fadeInUp">
					<p class="fs-80px fw-normal fs-sm-90px fs-md-142px text-custom-1 font-primary lh-1 top-0 position-absolute w-100 z-index-1">Glowing Gift</p>
					<p class="position-relative z-index-2 fs-15px mb-6 ls-1 text-body-emphasis fw-semibold">OUR GIFT</p>
				<h2 class="mb-4 position-relative z-index-2">Because you need best gifts for best occasions</h2>
				</div>
				<div class="row gy-8">

				@await Component.InvokeAsync("Gift")

					
				</div>
				<div class="text-center mt-12">
				<a asp-action="Gifts" asp-controller="Home" target="_blank" class="btn btn-outline-dark" data-animate="fadeInUp">
						Shop All Product
					</a>
				</div>
			</div>
		</section>

	<section>

		<div class="container">
			<div class="row gy-30px gx-30px">
				<div class="col-12 col-lg-5" data-animate="fadeInUp">
					<div class="card border-0 rounded-0 banner-09" data-bs-theme="light">
						<img class="card-img object-fit-cover" width="450" height="450" src="./assets/images/banner/banner-48.jpg" alt="25% off Everything"><div class="card-img-overlay d-inline-flex flex-column ps-md-13 pt-md-15 px-10 py-15">
							<h3 class="card-title lh-52px fw-semibold mw-xl-60 mw-lg-0 w-md-80 mb-7 fs-42px">25% off Everything</h3><p class="card-text fs-18px w-md-70 text-body">Makeup with extended range in colors for every human.</p><div class="mt-7"><a href="#" class="btn btn btn-dark btn-hover-bg-primary border-0 fs-6 text-white">Shop Sale</a></div>
						</div>
					</div>

				</div>
				<div class="col-12 col-lg-7" data-animate="fadeInUp">
					<div class="card border-0 rounded-0 banner-06 hover-zoom-in hover-shine">

						<img class="lazy-image w-100 card-img object-fit-cover  light-mode-img" src="~/images1/wedding-gift-for-couple-personalised-candle (1).webp" data-src="" width="690" height="450" alt="">
@*						<img class="lazy-image dark-mode-img w-100 card-img object-fit-cover " src="#" data-src="./assets/images/banner/banner-white-46.jpg" width="690" height="450" alt=""><div class="card-img-overlay">
*@							<div class="position-absolute top-50 end-0 translate-middle-y px-md-0 px-12">
								<div class="mt-7"></div>
							</div>

						</div>
					</div>

				</div>
			</div>
			<div class="row mt-0 gy-30px gx-30px" data-animate="fadeInUp">
				<div class="col-12 col-lg-7">
					<div class="card border-0 rounded-0 banner-06 hover-zoom-in hover-shine">

@*						<img class="lazy-image w-100 card-img object-fit-cover  light-mode-img" src="#" data-src="./assets/images/banner/banner-47.jpg" width="690" height="450" alt="">
*@						<img class="lazy-image dark-mode-img w-100 card-img object-fit-cover " src="~/images1/beautiful-cheerful-happy-young-girl-with-christmas-gifts-background-new-year-tree-home_324489-3990.jpg" data-src="" width="690" height="450" alt=""><div class="card-img-overlay">
							<div class="position-absolute top-50 end-0 translate-middle-y px-md-0 px-12">
								<div class="mt-7"></div>
							</div>

						</div>
					</div>

				</div>
				<div class="col-12 col-lg-5" data-animate="fadeInUp">
					<div class="card border-0 rounded-0 banner-09" data-bs-theme="light">
						<img class="card-img object-fit-cover" width="450" height="450" src="./assets/images/banner/banner-48.jpg" alt="Get The Skin You Want To Feel"><div class="card-img-overlay d-inline-flex flex-column ps-md-13 pt-md-15 px-10 py-15">
							<h3 class="card-title lh-52px fw-semibold mb-7 fs-42px">Get The Skin You Want To Feel</h3><p class="card-text fs-18px w-md-70 text-body">Makeup with extended range in colors for every human.</p><div class="mt-7"><a href="#" class="btn btn btn-dark btn-hover-bg-primary border-0 fs-6 text-white">Shop Now</a></div>
						</div>
					</div>

				</div>

			</div>
		</div>

	</section>
		@*<section class="pt-lg-17 pb-lg-18 pt-15 pb-16">

		
		</section>*@
	@await Component.InvokeAsync("Testimonial")

	</main>
	


	

GiftStore/Views/Home/TestimonialError.cshtml
@{
    ViewData["Title"] = "TestimonialError";
}


<h2 style="color: red;">@ViewBag.Message</h2>

@*<p>إذا كان لديك أي استفسارات، يرجى الاتصال بالدعم.</p>
*@

@*<a href="@Url.Action("Index", "Home")">العودة إلى الصفحة الرئيسية</a>
*@<a class="btn btn-primary" asp-action="Index" asp-controller="Home">Back to home</a>